modLoader="javafml"
loaderVersion="[40,)"
license="MIT"

[[mods]]
    modId="inventoryvaults"
    version="${file.jarVersion}"
    displayName="Inventory Vaults"
    authors="Carlsu"
    description='''
Switch between inventories for different purposes.
Example: Separate inventory for creative world/mode
'''

[[dependencies.inventoryvaults]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.inventoryvaults]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.inventoryvaults]]
    modId="cosmeticarmorreworked"
    mandatory=false
    versionRange="[1.18.2-v3x]"
    ordering="NONE"
    side="BOTH"